### ISSUE TITLE
koa2 support

### ISSUE THREAD

**Issue by ghost** [koajs/html-minifier#2]
Is there any plans to support koa2?

I've forked this repo and done the changes myself. All the (adapted to koa2) tests passed.
I don't know what to do next in order to, maybe, have my changes merged in this repo.
Should I push my local "koa2" branch to my forked repo and make the pull request from there?
This is my first time doing this so, please, apologize me for doing such a stupid issue.

**Comment by juliangruber** [comment]
yes, please push your local branch to your fork and then create a pull request, it will automatically be directed at this repo

**Comment by vtfn** [comment]
OK but first I have to make sure about some things.

As my english is very bad I don't thing it's a good idea I change the readme file, is it possible for you to change that after I pull the request?

Should I make any change in the package.json file besides the version of koa that is been used in the tests?

Since I'm using node 4.4.3, I was getting an error when running the npm's test script due the ```--harmony-generators```. I've remove the flag to run my local tests but I should leave it as it was when I forked, right?

And I couldn't run the other two test scripts because I on windows 10 e those don't seem to work on windows. Any problem with that?

Again I don't understand a lot of things about this kind of contribution. I know I should study before start doing anything but I think I just got too exited doing this.

**Comment by juliangruber** [comment]
> As my english is very bad I don't thing it's a good idea I change the readme file, is it possible for you to change that after I pull the request?

Sure we can do that

> Should I make any change in the package.json file besides the version of koa that is been used in the tests?

Nope, that's better left to the maintainers.

> Since I'm using node 4.4.3, I was getting an error when running the npm's test script due the --harmony-generators. I've remove the flag to run my local tests but I should leave it as it was when I forked, right?

You can include the removal of the harmony flag in its own commit inside the pull request, then we can decide whether to merge it as well.

> And I couldn't run the other two test scripts because I on windows 10 e those don't seem to work on windows. Any problem with that?

When you submit the pull request, travis should run the tests as well and that will show how the tests run on *nix machines. In general I'd say it would be a good idea for you to get a VM running ubuntu or something like that, for testing this stuff.

> Again I don't understand a lot of things about this kind of contribution. I know I should study before start doing anything but I think I just got too exited doing this.

No worries, keep your momentum and hack away!

**Comment by vtfn** [comment]
Ok thanks for the answers. The pull request is done. please let me know anything that I could've be done better.

**Comment by roastlechon** [comment]
Looks like its supported already, this should be closed
